-- Least-privilege role model aligned with the bootstrap SQL, dbt profile and Airflow DAG.
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ROLE_TRANSFORM;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_AUDITOR;
CREATE ROLE IF NOT EXISTS ROLE_DATA_PLATFORM_ADMIN;

GRANT ROLE ROLE_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE ROLE_TRANSFORM TO ROLE SYSADMIN;
GRANT ROLE ROLE_ANALYST TO ROLE SYSADMIN;
GRANT ROLE ROLE_AUDITOR TO ROLE SYSADMIN;
GRANT ROLE ROLE_DATA_PLATFORM_ADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE WH_INGEST_XS TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE, OPERATE ON WAREHOUSE WH_TRANSFORM_M TO ROLE ROLE_TRANSFORM;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS_S TO ROLE ROLE_ANALYST;

GRANT USAGE ON DATABASE ENTERPRISE_DWH TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON DATABASE ENTERPRISE_DWH TO ROLE ROLE_TRANSFORM;
GRANT USAGE ON DATABASE ENTERPRISE_DWH TO ROLE ROLE_ANALYST;
GRANT USAGE ON DATABASE ENTERPRISE_DWH TO ROLE ROLE_AUDITOR;

GRANT USAGE ON SCHEMA ENTERPRISE_DWH.RAW TO ROLE ROLE_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT, CREATE PIPE, CREATE TASK ON SCHEMA ENTERPRISE_DWH.RAW TO ROLE ROLE_DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ENTERPRISE_DWH.RAW TO ROLE ROLE_DATA_ENGINEER;

GRANT USAGE ON SCHEMA ENTERPRISE_DWH.RAW TO ROLE ROLE_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ENTERPRISE_DWH.RAW TO ROLE ROLE_TRANSFORM;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ENTERPRISE_DWH.STAGING TO ROLE ROLE_TRANSFORM;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ENTERPRISE_DWH.RAW_VAULT TO ROLE ROLE_TRANSFORM;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ENTERPRISE_DWH.MARTS TO ROLE ROLE_TRANSFORM;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ENTERPRISE_DWH.FEATURES TO ROLE ROLE_TRANSFORM;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ENTERPRISE_DWH.OBSERVABILITY TO ROLE ROLE_TRANSFORM;

GRANT USAGE ON SCHEMA ENTERPRISE_DWH.MARTS TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA ENTERPRISE_DWH.FEATURES TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ENTERPRISE_DWH.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ENTERPRISE_DWH.MARTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ENTERPRISE_DWH.FEATURES TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ENTERPRISE_DWH.FEATURES TO ROLE ROLE_ANALYST;

GRANT USAGE ON SCHEMA ENTERPRISE_DWH.OBSERVABILITY TO ROLE ROLE_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ENTERPRISE_DWH.OBSERVABILITY TO ROLE ROLE_AUDITOR;
